### ISSUE TITLE
semantic map

### ISSUE THREAD

**Issue by liucsg** [vvasilo/semnav#1]
Hi, I have two questions.
1. what's representation of object in semantic map, including the relationship between objects?
2. How to find a person after disappearing from the field of vision for robotic?

**Comment by vvasilo** [comment]
Hi @liucsg ,
1. For the semantic map, we use an external module that provides a message of type SemanticMapObjectArray - the SemanticMapObject message (https://github.com/vvasilo/semnav/blob/master/extras/object_pose_interface_msgs/msg/SemanticMapObject.msg) contains an object classification, the pose of the object in 3D and the associated keypoints with respect to the center of mass.
2. The person detection is more heuristic (just frame by frame), and the robot "remembers" the position in the map it last saw a human and tries to navigate there.
