### ISSUE TITLE
Determining the Pose of the object in semantic map

### ISSUE THREAD

**Issue by aaravrav142** [vvasilo/semnav#2]
Hi, 
Can you explain how you determine the pose of the detected objects in the generated map? Can you point me to the code where this is implemented? Thanks.

**Comment by vvasilo** [comment]
Hello, 
Please check out [this](https://github.com/seanbow/object_pose_detection) package for the semantic map implementation. The used messages are included [here](https://github.com/vvasilo/semnav/tree/master/extras/object_pose_interface_msgs).
